### ISSUE TITLE
Issue with referral program module - throws 500 error on duplicate email

### ISSUE THREAD

**Issue by x97wehner** [thirtybees/referralprogram#9]
Hi,

I had a customer trying to refer his fried, but every time would get a 500 error page. I investigated and found that the friend had been submitted for referral a couple years back but had never reacted to it. I was able to manually fix it for them, but the 500 error shouldn't be happening. Can we script in an error message instead that says "This person has already been referred to our company" or something similar, rather that the 500 page?

Screenshot is attached
![error](https://user-images.githubusercontent.com/44684415/183430755-1153acf7-0326-48c9-a9d9-1df85c89e025.png)

**Comment by getdatakick** [comment]
Please provide stacktrace
